name: CI Tests

on:
  pull-request:
    branches: [master]

jobs:
  run-test:
    name: 'Tests runs...'
    runs-on: ubuntu-latest

    steps:
      - name: Git clone
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Cache Maven
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('./pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Maven test
        run: mvn test
